### ISSUE TITLE
Ideas for `https://github.com/opentable/oc-testing`

### ISSUE THREAD

**Issue by mattiaerre** [mattiaerre/oc-hub#1]
# Description

I really enjoy working w/ Jest nowadays and I believe that is a very good choice for testing JavaScript both client and server side; I've created this repo that I am using in order to collect the components that I am building and I would like to share w/ you [oc-timeago](https://github.com/mattiaerre/oc-hub/tree/master/oc-timeago).

As you can see there is a `server.spec.js` file containing tests asserting against the model; I'd love to use the same approach in order to refactor the `oc-testing` repository that uses at the moment mocha & chai instead of Jest.

If you think this is a good idea I will proceed as soon as possible w/ a PR.

P.S. is it possible to have `moment` available at the `https://oc-registry.herokuapp.com/` registry so that we will be able to have a running version of the `oc-timeago` component? Thanks!

// cc @matteofigus @nickbalestra

**Comment by matteofigus** [comment]
I love jest and love the idea. Only thing, I don't know if to keep both (jest + non jest) or just to include jest for everything. 

Perhaps including both options (mocha and jest tests) is good anyway as first step?

**Comment by mattiaerre** [comment]
@matteofigus let's try to do that: I will add additional tests done w/ Jest so that we can compare them and see which approach is better 😉  ... sounds like a plan?

**Comment by matteofigus** [comment]
awesome! Thanks :)

**Comment by mattiaerre** [comment]
this will be fixed w/ this PR:

https://github.com/opentable/oc-testing/pull/1

// @matteofigus

**Comment by mattiaerre** [comment]
closing because of

https://github.com/opencomponents/oc-testing/pull/1
